### ISSUE TITLE
sfftw.h error while installing namd3.0

### ISSUE THREAD

**Issue by TasneemAllam** [jvermaas/Software-Building-Instructions#1]
Hello, 
Iam working on an HPC enviroment and iam trying to install namd3.0 based on the documentation in the link below:
https://github.com/jvermaas/Software-Building-Instructions/blob/main/NAMD.md 
based on the procedure in NAMD on slurm-based clusters part 

The modules loaded on my enviroment below:
  $ module load CUDA
  $ module load OpenMPI
  $ module load Tcl/8.6.10-GCCcore-9.3.0
  $ module load FFTW/3.3.8-intel-2020a
  $ module load FFTW/3.3.8-gompi-2019a

While trying to install namd3.0 after executing "make -j8" command i got the errors below: 

src/ComputePme.C:19:10: fatal error: sfftw.h: No such file or directory
   19 | #include <sfftw.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [obj/ComputePme.o] Error 1
make: *** Waiting for unfinished jobs....
src/Node.C: In constructor ‘Node::Node(GroupInitMsg*)’:
src/Node.C:351:28: error: ‘ck_get_GNI_BIConfig’ was not declared in this scope
  351 |     balancedInjectionLevel=ck_get_GNI_BIConfig();
      |                            ^~~~~~~~~~~~~~~~~~~
src/Node.C:353:5: error: ‘ck_set_GNI_BIConfig’ was not declared in this scope
  353 |     ck_set_GNI_BIConfig(20);
      |     ^~~~~~~~~~~~~~~~~~~
src/Node.C: In member function ‘void Node::startup()’:
src/Node.C:886:7: error: ‘ck_set_GNI_BIConfig’ was not declared in this scope
  886 |       ck_set_GNI_BIConfig(balancedInjectionLevel);
      |       ^~~~~~~~~~~~~~~~~~~
make: *** [obj/Node.o] Error 1
 
If there is something missing in my procedure please let me know.

Thanks in advance.

**Comment by jvermaas** [comment]
NAMD's build system can't find sfftw.h. It only looks in the directory specified by ./arch/Linux-x86_64.fftw3 (assuming you are building for x86_64 linux), which probably don't have your header files in them.

**Comment by TasneemAllam** [comment]
Can you please suggest how can we solve this error? Thanks

**Comment by jvermaas** [comment]
I did. Edit arch/Linux-x86_64.fftw3 to point at the right set of directories.

**Comment by TasneemAllam** [comment]
I got this error 

while trying to make -j8 

obj/tcl_main.o:tcl_main.c:function main: error: undefined reference to 'Tcl_MainEx'
collect2: error: ld returned 1 exit status
make: *** [psfgen] Error 1
make: *** Waiting for unfinished jobs....

Can you please suggest how to solve it?

**Comment by jvermaas** [comment]
Probably the same story, but for -ltcl8.5 (or 8.6). This depends on what is in arch/Linux-x86_64.tcl. Undefined references happen at link time, when the system can't find the appropriate library. I didn't run into this because my supercomputing resources add these directories to the include and library paths, so the compilers can find the needed libraries no matter what.

**Comment by TasneemAllam** [comment]
While trying make -j8 again 

In file included from /eb/software/CUDA/10.1.243-iccifort-2019.5.281/include/cuda_runtime.h:83,
                 from <command-line>:
/eb/software/CUDA/10.1.243-iccifort-2019.5.281/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
/eb/software/CUDA/10.1.243-iccifort-2019.5.281/bin/nvcc -Xcompiler "-m64" -O3 --maxrregcount 48 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_75,code=compute_75 -DNAMD_CUDA -I. -I.rootdir/cub -I/eb/software/CUDA/10.1.243-iccifort-2019.5.281/include  -use_fast_math -Xptxas -v -o obj/ComputeNonbondedCUDAKernel.o -c `echo src/`ComputeNonbondedCUDAKernel.cu
In file included from /eb/software/CUDA/10.1.243-iccifort-2019.5.281/include/cuda_runtime.h:83,
                 from <command-line>:
/eb/software/CUDA/10.1.243-iccifort-2019.5.281/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~

**Comment by TasneemAllam** [comment]
when i try to load modules with GCC 8 it exit with error 2 .
May i ask which GCC version should be used?

**Comment by jvermaas** [comment]
https://stackoverflow.com/questions/6622454/cuda-incompatible-with-my-gcc-version, which points to https://gist.github.com/ax3l/9489132

Basically, your GCC version is forced to be <= 8 because you are using CUDA 10.1.

**Comment by TasneemAllam** [comment]
May i ask what is the recommended version for CUDA to be compatible?

**Comment by TasneemAllam** [comment]
obj/tcl_main.o:tcl_main.c:function main: error: undefined reference to 'Tcl_MainEx'
collect2: error: ld returned 1 exit status
